In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [38]:
# GENERATION OF SYNTHETIC DATA
number_data_points = 1000
lambda1 = 2  # Scale parameter for the first exponential distribution
lambda2 = 10  # Scale parameter for the second exponential distribution
pi1 = 0.6  # Mixing proportion for the first exponential distribution
pi2 = 1 - pi1  # Mixing proportion for the second exponential distribution

number_state1 = np.random.binomial(number_data_points, pi1)
number_state2 = number_data_points - number_state1

# Generate samples from each exponential distribution
samples1 = np.random.exponential(1 / lambda1, size=number_state1)
samples2 = np.random.exponential(1 / lambda2, size=number_state2)

# Combine the samples from both distributions
samples = np.concatenate([samples1, samples2])
# np.random.shuffle(samples)  # Shuffle the combined samples to ensure random ordering

In [39]:
# GIBBS PARAMETERS
alpha = 1
beta = 1
large_M = 2  # define "weak limit"
initial_value_rates = 3.4
rate_array = np.full(large_M, initial_value_rates)
pi_array = np.full(large_M, 1 / large_M)
# this outputs an array of integers from 1 to large_M
categories = np.arange(1, large_M + 1)

gibbs_iterations = 1000
# Initiate the array coinciding with the number of Gibbs samples and the output of each
sample_array = np.zeros((gibbs_iterations, number_data_points))

In [54]:
# Define emission distribution for multiple species indices
def cat_prob_for_multiple_species(sample, rate_array, pi_array):
    # print(rate_array)
    # print(pi_array)
    result_arrays = rate_array * np.exp(-sample * rate_array) * pi_array
    # print(result_arrays)
    return result_arrays / np.sum(result_arrays)


print(cat_prob_for_multiple_species(1, rate_array, pi_array))
# print(sum(cat_prob_for_multiple_species(2)))
# print(categories)

[0.99891682 0.00108318]


In [55]:
count_array = np.zeros(large_M)  # Initialize array of counts
beta_sum_array = np.zeros(large_M)  # Initialize array of counts
for i in range(gibbs_iterations):
    count_array.fill(0)  # Initialize array of counts
    beta_sum_array.fill(0)  # Initialize array of counts

    for d in range(number_data_points):  # sample the s's
        probs = cat_prob_for_multiple_species(samples[d], rate_array, pi_array)
        sn = np.random.choice(
            categories,
            p=probs,
        )
        sample_array[i, d] = sn
        count_array[sn - 1] += 1
        beta_sum_array[sn - 1] += samples[d]
    print(count_array)
    # print(sum(samples))

    rate_array = 1 / np.array([lambda1, lambda2])
    # np.random.gamma(alpha + count_array, 1 / (1 / beta + beta_sum_array))
    pi_prob_array = alpha / large_M + count_array / number_data_points
    pi_array = np.random.dirichlet(pi_prob_array)


# print(samples)
print(sample_array)

[999.   1.]
[999.   1.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[999.   1.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[999.   1.]
[1000.    0.]
[998.   2.]
[999.   1.]
[1000.    0.]
[999.   1.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[999.   1.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[999.   1.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[1000.    0.]
[999.   1.]
[998.   2.]


In [51]:
cat_prob_for_multiple_species(samples[1], 1/np.array([lambda1,lambda2]), np.array([pi1,pi2]))

[0.5 0.1]
[0.6 0.4]
[0.14344853 0.03451238]


array([0.80606762, 0.19393238])

In [52]:
samples[1]

1.475612395794363

In [43]:
0.5*np.exp(-0.5*0.141)*0.6

0.27957832185774006

In [44]:
0.1*np.exp(-0.1*0.141)*0.4

0.039439957577550366

In [10]:
np.array([1,2])

array([1, 2])

In [11]:
test = np.array([1,2,3,4])

In [12]:
test.fill(0)

In [13]:
test

array([0, 0, 0, 0])

In [14]:
np.random.gamma(1 + rate_array, 1 / (1 / beta + rate_array))

array([2.03653178, 0.84012068])