In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# GENERATION OF SYNTHETIC DATA
number_data_points = 1000
lambda1 = 2  # Scale parameter for the first exponential distribution
lambda2 = 4  # Scale parameter for the second exponential distribution
pi1 = 0.6  # Mixing proportion for the first exponential distribution
pi2 = 1 - pi1  # Mixing proportion for the second exponential distribution

samples1 = np.random.exponential(
    1 / lambda1, size=int(pi1 * number_data_points)
)  # Generate samples from each exponential distribution
samples2 = np.random.exponential(1 / lambda2, size=int(pi2 * number_data_points))

samples = np.concatenate(
    [samples1, samples2]
)  # Combine the samples from both distributions
# np.random.shuffle(samples)  # Shuffle the combined samples to ensure random ordering

In [8]:
# GIBBS PARAMETERS
alpha = 1
beta = 1
gibbs_iterations = 100
large_M = 2  # define "weak limit"
initial_value_rates = 3.4
rate_array = np.full(
    large_M, initial_value_rates
)  # [0.01, 10.0] #np.full(large_M, initial_value_rates)
# rate_array = np.array([2.0, 4.0])
pi_array = np.full(large_M, 1 / large_M)  # [0.7, 0.3] # np.full(large_M, 1/large_M)
# pi_array = np.array([0.7, 0.3])
categories = np.arange(
    1, large_M + 1
)  # this outputs an array of integers from 1 to large_M


# Define emission distribution for multiple species indices
def cat_prob_for_multiple_species(data_index, rate_array):
    result_arrays = []  # List to store the arrays for each species index
    for species_index in range(large_M):
        result_array = (
            rate_array[species_index]
            * np.exp(-samples[data_index] * rate_array[species_index])
            * pi_array[species_index]
        )
        result_arrays.append(result_array)
    return result_arrays / np.sum(result_arrays)


print(cat_prob_for_multiple_species(1, rate_array))
# print(sum(cat_prob_for_multiple_species(2)))
# print(categories)

sample_array = np.zeros(
    (gibbs_iterations, number_data_points)
)  # Initiate the array coinciding with the number of Gibbs samples and the output of each

[0.5 0.5]


In [9]:
for i in range(gibbs_iterations):
    count_array = np.zeros(large_M)  # Initialize array of counts
    beta_sum_array = np.zeros(large_M)  # Initialize array of counts
    pi_prob_array = np.zeros(large_M)

    for d in range(number_data_points):  # sample the s's
        sn = np.random.choice(
            categories, p=cat_prob_for_multiple_species(d, rate_array)
        )
        sample_array[i, d] = sn
        count_array[sn - 1] += 1
        beta_sum_array[sn - 1] += samples[d]
        # print(cat_prob_for_multiple_species)
    for d in range(large_M):
        rate_array[d] = np.random.gamma(
            alpha + count_array[d], 1 / (1 / beta + beta_sum_array[d])
        )
        pi_prob_array[d] = alpha / large_M + count_array[d] / number_data_points
        # print(pi_prob_array)
    print(pi_prob_array)
    pi_array = np.random.dirichlet(pi_prob_array)


# print(samples)
print(sample_array)

[1.015 0.985]
[1.365 0.635]
[1.456 0.544]
[1.461 0.539]
[1.23 0.77]
[1.451 0.549]
[1.496 0.504]
[0.729 1.271]
[0.618 1.382]
[0.513 1.487]
[0.57 1.43]
[0.538 1.462]
[0.503 1.497]
[0.769 1.231]
[1.198 0.802]
[1.384 0.616]
[1.359 0.641]
[1.464 0.536]
[1.359 0.641]
[1.469 0.531]
[0.821 1.179]
[1.5 0.5]
[1.37 0.63]
[1.242 0.758]
[0.594 1.406]
[0.556 1.444]
[0.688 1.312]
[0.602 1.398]
[0.507 1.493]
[0.928 1.072]
[0.604 1.396]
[0.62 1.38]
[0.756 1.244]
[1.363 0.637]
[0.503 1.497]
[0.514 1.486]
[0.508 1.492]
[0.525 1.475]
[0.648 1.352]
[0.885 1.115]
[0.663 1.337]
[0.572 1.428]
[0.68 1.32]
[0.926 1.074]
[1.193 0.807]
[1.194 0.806]
[0.784 1.216]
[0.557 1.443]
[0.812 1.188]
[0.859 1.141]
[1.117 0.883]
[0.717 1.283]
[1.014 0.986]
[1.198 0.802]
[1.435 0.565]
[1.184 0.816]
[1.449 0.551]
[1.133 0.867]
[1.429 0.571]
[1.21 0.79]
[1.299 0.701]
[1.337 0.663]
[1.049 0.951]
[1.174 0.826]
[1.432 0.568]
[1.111 0.889]
[0.81 1.19]
[0.56 1.44]
[0.923 1.077]
[1.254 0.746]
[1.377 0.623]
[1.418 0.582]
[1.049 0.951

In [41]:
range(large_M)

range(0, 1)

In [42]:
categories

array([1])

In [43]:
print(rate_array)

[2.04593116]


In [2]:
np.full(2,1)

array([1, 1])

In [5]:
np.array([1,2])

array([1, 2])